name: "UTBot Java: build and run tests"

permissions: read-all

on:  
  push:
    branches:
      - 'main'
      - 'unit-test-bot/r**'
  pull_request:
    branches:
      - 'main'
      - 'unit-test-bot/r**'

jobs:
  build-and-run-tests:
    uses: ./.github/workflows/build-and-run-tests-from-branch.yml
    secrets: inherit
